package com.cardcaller.magic

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.media.RingtoneManager
import android.os.*
import androidx.compose.foundation.*
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.input.pointer.*
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import java.text.SimpleDateFormat
import java.util.*

private val Navy=Color(0xFF07111F);private val Surface=Color(0xFF122238);private val Green=Color(0xFF3DDC84);private val Danger=Color(0xFFE53935);private val Muted=Color(0xFF9FB0C5)
@Composable fun CardCallerApp(vm:CardCallerViewModel,u:UiState){MaterialTheme(colorScheme=darkColorScheme(primary=Green,background=Navy,surface=Surface,error=Danger)){Surface(Modifier.fillMaxSize(),color=Navy){when(u.screen){Screen.HOME->Home(vm);Screen.PICKER->Picker(vm,u,u.remoteMode);Screen.GESTURE->Gesture(vm,u);Screen.REMOTE->Remote(vm,u);Screen.INSTAGRAM->InstagramPublish(vm,u);Screen.SETTINGS->Settings(vm,u);Screen.HELP->Help(vm);Screen.WAITING->Waiting(vm,u);Screen.INCOMING->Incoming(vm,u);Screen.REVEAL->Reveal(vm,u)}}}}
@Composable private fun Page(title:String,onBack:()->Unit,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().statusBarsPadding().padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onBack){Icon(Icons.Default.ArrowBack,"뒤로")};Text(title,fontSize=25.sp,fontWeight=FontWeight.Bold)};Spacer(Modifier.height(12.dp));content()}}
@Composable fun Home(vm:CardCallerViewModel){val items=listOf("카드 직접 선택" to Screen.PICKER,"비밀 제스처 입력" to Screen.GESTURE,"원격 카드 전송" to Screen.REMOTE,"Instagram 공개" to Screen.INSTAGRAM,"공연 설정" to Screen.SETTINGS,"사용 방법" to Screen.HELP);Column(Modifier.fillMaxSize().statusBarsPadding().padding(20.dp)){Text("Card Caller",fontSize=34.sp,fontWeight=FontWeight.Bold,color=Green);Text("선택한 카드가 전화를 겁니다",color=Muted);Spacer(Modifier.height(18.dp));items.forEach{(n,s)->Card(Modifier.fillMaxWidth().padding(vertical=4.dp).clickable{vm.navigate(s)},colors=CardDefaults.cardColors(containerColor=Surface)){Text(n,Modifier.padding(18.dp),fontSize=19.sp)}};Spacer(Modifier.weight(1f));Text("마술 및 엔터테인먼트용 수신 화면 시뮬레이션",color=Muted,fontSize=12.sp,modifier=Modifier.align(Alignment.CenterHorizontally))}}
@Composable fun Picker(vm:CardCallerViewModel,u:UiState,remote:Boolean){Page(if(remote)"원격으로 보낼 카드" else "카드 직접 선택",{vm.navigate(if(remote)Screen.REMOTE else Screen.HOME)}){LazyVerticalGrid(GridCells.Fixed(4),Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(8.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){items(PlayingCard.deck){c->val chosen=u.selected==c;Card(Modifier.aspectRatio(.72f).clickable{vm.select(c)}.border(if(chosen)3.dp else 1.dp,if(chosen)Green else Muted,RoundedCornerShape(12.dp)),colors=CardDefaults.cardColors(containerColor=Color.White)){Box(Modifier.fillMaxSize()){Text("${c.suit.symbol}\n${c.rank.label}",color=if(c.suit in listOf(Suit.HEARTS,Suit.DIAMONDS))Color.Red else Color.Black,fontSize=23.sp,fontWeight=FontWeight.Bold,modifier=Modifier.align(Alignment.Center));if(chosen)Icon(Icons.Default.CheckCircle,"선택됨",tint=Green,modifier=Modifier.align(Alignment.TopEnd).padding(4.dp))}}}};u.selected?.let{if(remote){Button(onClick={vm.sendRemote(it)},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("카드 전송")}}else{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick={vm.schedule()},Modifier.weight(1f).heightIn(min=56.dp)){Text("전화 예약")};Button(onClick={vm.navigate(Screen.INSTAGRAM)},Modifier.weight(1f).heightIn(min=56.dp)){Text("Instagram 공개")}}}}}}
@Composable fun Gesture(vm:CardCallerViewModel,u:UiState){val context=LocalContext.current;var drag by remember{mutableStateOf(Offset.Zero)};Page("비밀 제스처 입력",{vm.navigate(Screen.HOME)}){Box(Modifier.weight(1f).fillMaxWidth().background(Surface,RoundedCornerShape(24.dp)).pointerInput(u.settings.gestureSensitivity){detectDragGestures(onDragStart={drag=Offset.Zero},onDrag={change,amount->change.consume();drag+=amount},onDragEnd={GestureInputManager.suit(drag.x,drag.y,u.settings.gestureSensitivity)?.let{vm.gestureSuit(it);haptic(context)}})}.pointerInput(Unit){detectTapGestures(onTap={vm.tap();haptic(context)},onLongPress={vm.resetGesture();haptic(context)})}.semantics{contentDescription="제스처 입력 영역"},contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.TouchApp,null,Modifier.size(64.dp),tint=Green);Text("스와이프로 무늬 · 탭 횟수로 숫자",color=Muted);Text("2초 이상 길게 눌러 초기화",color=Muted,fontSize=12.sp);if(!u.settings.hideGestureResult)Text("${u.gestureSuit?.symbol?:"?"} ${GestureInputManager.rank(u.taps)?.label?:"?"}",fontSize=46.sp)}};u.selected?.let{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick={vm.schedule()},Modifier.weight(1f).heightIn(min=56.dp)){Text("전화 예약")};Button(onClick={vm.navigate(Screen.INSTAGRAM)},Modifier.weight(1f).heightIn(min=56.dp)){Text("Instagram 공개")}}}}}
private fun haptic(c:Context){if(Build.VERSION.SDK_INT>=31)(c.getSystemService(Context.VIBRATOR_MANAGER_SERVICE)as VibratorManager).defaultVibrator.vibrate(VibrationEffect.createOneShot(30,80))else @Suppress("DEPRECATION")(c.getSystemService(Context.VIBRATOR_SERVICE)as Vibrator).vibrate(30)}
@Composable fun Remote(vm:CardCallerViewModel,u:UiState){var code by remember{mutableStateOf("")};Page("원격 카드 전송",{vm.navigate(Screen.HOME)}){Text("공연폰",fontWeight=FontWeight.Bold);Button(onClick=vm::createRoom,Modifier.fillMaxWidth()){Text("6자리 방 만들기")};if(u.roomCode.isNotEmpty())Text(u.roomCode,fontSize=40.sp,color=Green,modifier=Modifier.align(Alignment.CenterHorizontally));Spacer(Modifier.height(20.dp));Text("리모컨폰",fontWeight=FontWeight.Bold);OutlinedTextField(code,{code=it.filter(Char::isDigit).take(6)},label={Text("방 코드")},modifier=Modifier.fillMaxWidth());Button(onClick={vm.join(code)},Modifier.fillMaxWidth()){Text("방 연결")};Text("상태: ${u.connection.name}",color=Muted);u.error?.let{Text(it,color=Danger)};if(u.connection==ConnectionState.CONNECTED){Spacer(Modifier.height(12.dp));Button(onClick=vm::openRemotePicker,Modifier.fillMaxWidth()){Text("카드 선택 및 전송")}};Spacer(Modifier.weight(1f));Text("Firebase 미설정 상태에서도 직접 선택과 제스처는 정상 동작합니다.",color=Muted,fontSize=12.sp)}}
@Composable fun InstagramPublish(vm:CardCallerViewModel,u:UiState){val card=u.selected?:u.lastCard;val context=LocalContext.current;Page("Instagram 공개",{vm.navigate(Screen.HOME)}){if(card==null){Box(Modifier.weight(1f).fillMaxWidth(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.PhotoCamera,null,Modifier.size(64.dp),tint=Green);Text("먼저 카드를 입력하세요",fontSize=22.sp);Text("직접 선택, 비밀 제스처 또는 원격 전송을 사용할 수 있습니다.",color=Muted)}};Button(onClick={vm.navigate(Screen.PICKER)},Modifier.fillMaxWidth()){Text("카드 선택")};return@Page};Column(Modifier.weight(1f).fillMaxWidth(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){CardSymbol(card,180);Spacer(Modifier.height(18.dp));Text(card.display(CardDisplayFormat.KOREAN),fontSize=28.sp,fontWeight=FontWeight.Bold);Text("@${u.instagramAccount.username}",color=Muted);Spacer(Modifier.height(28.dp));when(u.instagramStatus){InstagramPublishStatus.PUBLISHING,InstagramPublishStatus.RETRYING->{CircularProgressIndicator();Text(if(u.instagramStatus==InstagramPublishStatus.RETRYING)"재시도 중…" else "게시 중…",color=Muted)};InstagramPublishStatus.SUCCEEDED->{Icon(Icons.Default.CheckCircle,"게시 성공",Modifier.size(54.dp),tint=Green);Text("게시 성공",fontSize=22.sp);Button(onClick={context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(u.instagramAccount.profileUrl)))}){Text("Instagram에서 확인")}};InstagramPublishStatus.FAILED->{Icon(Icons.Default.Error,"게시 실패",Modifier.size(54.dp),tint=Danger);Text("게시 실패",fontSize=22.sp);Text(u.error?:"알 수 없는 오류",color=Muted);Button(onClick={vm.publishInstagram(true)}){Text("재시도")}};else->{}}};if(u.instagramStatus in listOf(InstagramPublishStatus.IDLE,InstagramPublishStatus.CONFIRMING)){Button(onClick={vm.confirmInstagram(InstagramPublishType.STORY)},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("스토리로 공개")};OutlinedButton(onClick={vm.confirmInstagram(InstagramPublishType.FEED)},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("피드 게시물로 공개")}};u.error?.takeIf{u.instagramStatus==InstagramPublishStatus.IDLE}?.let{Text(it,color=Danger)};if(u.instagramStatus==InstagramPublishStatus.CONFIRMING){AlertDialog(onDismissRequest=vm::cancelInstagramConfirm,title={Text("게시 전 확인")},text={Column(horizontalAlignment=Alignment.CenterHorizontally){CardSymbol(card,120);Text("@${u.instagramAccount.username}");Text(if(u.instagramType==InstagramPublishType.STORY)"스토리" else "피드 게시물")}},confirmButton={Button(onClick={vm.publishInstagram(false)}){Text("게시")}},dismissButton={TextButton(onClick=vm::cancelInstagramConfirm){Text("취소")}})}}}
@Composable fun Settings(vm:CardCallerViewModel,u:UiState){var s by remember(u.settings){mutableStateOf(u.settings)};Page("공연 설정",{vm.navigate(Screen.HOME)}){Column(Modifier.verticalScroll(rememberScrollState())){Text("전화 지연: ${s.delaySeconds}초");Slider(s.delaySeconds.toFloat(),{s=s.copy(delaySeconds=it.toInt())},valueRange=0f..10f,steps=9);SettingSwitch("진동",s.vibrate){s=s.copy(vibrate=it)};SettingSwitch("벨소리",s.ringtone){s=s.copy(ringtone=it)};SettingSwitch("화면 밝기 최대",s.maxBrightness){s=s.copy(maxBrightness=it)};SettingSwitch("제스처 결과 숨기기",s.hideGestureResult){s=s.copy(hideGestureResult=it)};SettingSwitch("화면 뒤집기 실행",s.flipTrigger){s=s.copy(flipTrigger=it)};SettingSwitch("볼륨 버튼 실행",s.volumeTrigger){s=s.copy(volumeTrigger=it)};SettingSwitch("마지막 카드 자동 삭제",s.clearLastCard){s=s.copy(clearLastCard=it)};Text("제스처 민감도: ${s.gestureSensitivity.toInt()}");Slider(s.gestureSensitivity,{s=s.copy(gestureSensitivity=it)},valueRange=30f..200f);Text("카드 표시 형식");EnumButtons(CardDisplayFormat.entries,s.displayFormat){s=s.copy(displayFormat=it)};Text("수신 화면 테마");EnumButtons(CallTheme.entries,s.callTheme){s=s.copy(callTheme=it)};Button(onClick={vm.saveSettings(s);vm.navigate(Screen.HOME)},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("설정 저장")}}}}
@Composable private fun SettingSwitch(n:String,v:Boolean,set:(Boolean)->Unit){Row(Modifier.fillMaxWidth().heightIn(min=56.dp),verticalAlignment=Alignment.CenterVertically){Text(n,Modifier.weight(1f));Switch(v,set)}}
@Composable private fun <T> EnumButtons(xs:List<T>,v:T,set:(T)->Unit){Row(Modifier.horizontalScroll(rememberScrollState())){xs.forEach{x->FilterChip(x==v,{set(x)},label={Text(x.toString())},modifier=Modifier.padding(end=6.dp))}}}
@Composable fun Waiting(vm:CardCallerViewModel,u:UiState){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){CircularProgressIndicator();Spacer(Modifier.height(20.dp));Text("전화 대기 중…",fontSize=24.sp);Text("${u.settings.delaySeconds}초 후 실행",color=Muted);Button(vm::triggerNow){Text("지금 실행")};TextButton(vm::home){Text("취소")}}}}
@Composable fun Incoming(vm:CardCallerViewModel,u:UiState){val c=u.selected?:return;val context=LocalContext.current;var now by remember{mutableStateOf(Date())};DisposableEffect(Unit){val vibrator=if(Build.VERSION.SDK_INT>=31)(context.getSystemService(Context.VIBRATOR_MANAGER_SERVICE)as VibratorManager).defaultVibrator else @Suppress("DEPRECATION")(context.getSystemService(Context.VIBRATOR_SERVICE)as Vibrator);val ringtone=if(u.settings.ringtone)runCatching{RingtoneManager.getRingtone(context,RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE)).also{it.play()}}.getOrNull() else null;if(u.settings.vibrate)vibrator.vibrate(VibrationEffect.createWaveform(longArrayOf(0,500,500),0));onDispose{ringtone?.stop();vibrator.cancel()}};LaunchedEffect(Unit){while(true){now=Date();delay(1000)}};Column(Modifier.fillMaxSize().statusBarsPadding().padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(SimpleDateFormat("HH:mm",Locale.getDefault()).format(now),fontSize=18.sp);Text("수신 전화",color=Muted);Spacer(Modifier.weight(.5f));CardSymbol(c,150);Spacer(Modifier.height(24.dp));Text(c.display(u.settings.displayFormat,u.settings.customCallerName),fontSize=36.sp,fontWeight=FontWeight.Bold);Text("카드가 전화를 걸고 있습니다…",color=Muted);Spacer(Modifier.weight(1f));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceAround){CallButton(Danger,Icons.Default.CallEnd,"거절",vm::reject);CallButton(Green,Icons.Default.Call,"수신",vm::accept)}}}
@Composable private fun CallButton(color:Color,icon:androidx.compose.ui.graphics.vector.ImageVector,label:String,onClick:()->Unit){Column(horizontalAlignment=Alignment.CenterHorizontally){IconButton(onClick,Modifier.size(76.dp).background(color,CircleShape)){Icon(icon,label,Modifier.size(36.dp),tint=Color.White)};Text(label)}}
@Composable private fun CardSymbol(c:PlayingCard,size:Int){Box(Modifier.size(size.dp).background(Color.White,CircleShape),contentAlignment=Alignment.Center){Text("${c.suit.symbol}\n${c.rank.label}",fontSize=(size/3).sp,lineHeight=(size/3).sp,color=if(c.suit in listOf(Suit.HEARTS,Suit.DIAMONDS))Color.Red else Color.Black,fontWeight=FontWeight.Bold)}}
@Composable fun Reveal(vm:CardCallerViewModel,u:UiState){val c=u.selected?:return;Column(Modifier.fillMaxSize().statusBarsPadding().padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){CardSymbol(c,220);Spacer(Modifier.height(30.dp));Text("당신이 선택한 카드는",color=Muted);Text("${c.suit.symbol} ${c.rank.label}입니다",fontSize=36.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(40.dp));Button({vm.navigate(Screen.PICKER)},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("다시 공연하기")};OutlinedButton(vm::home,Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("홈으로 돌아가기")}}}
@Composable fun Help(vm:CardCallerViewModel){Page("사용 방법",{vm.navigate(Screen.HOME)}){Column(Modifier.verticalScroll(rememberScrollState())){Text("이 앱은 실제 전화가 아닌 공연용 수신 화면 시뮬레이션입니다.",color=Green,fontWeight=FontWeight.Bold);Spacer(Modifier.height(16.dp));Text("1. 카드 직접 선택\n52장 중 카드를 고르고 전화 예약을 누르세요.\n\n2. 비밀 제스처\n위 ♠ · 오른쪽 ♥ · 아래 ♣ · 왼쪽 ♦. 탭 1~13회로 A~K를 입력합니다. 길게 누르면 초기화됩니다.\n\n3. 원격 연결\n공연폰에서 방을 만들고, 리모컨폰에서 같은 6자리 코드를 입력한 뒤 카드를 전송하세요.\n\n볼륨 트리거는 앱이 화면에 보일 때만 동작합니다.")}}}
