package com.cardcaller.magic

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

enum class Screen { HOME, PICKER, GESTURE, REMOTE, INSTAGRAM, MAGIC_LAB, SMART_DECK, SMART_DECK_SETTINGS, SMART_DECK_REHEARSAL, QR_PROPHECY, NOTIFICATION_PROPHECY, LIE_DETECTOR, PHOTO_MAGIC, MULTI_AUDIENCE, DEMO, REHEARSAL, SETTINGS, HELP, WAITING, INCOMING, AI_CALL, REVEAL, RESULT }
data class UiState(val screen:Screen=Screen.HOME,val selected:PlayingCard?=null,val lastCard:PlayingCard?=null,val settings:AppSettings=AppSettings(),val gestureSuit:Suit?=null,val taps:Int=0,val roomCode:String="",val connection:ConnectionState=ConnectionState.DISCONNECTED,val error:String?=null,val remoteMode:Boolean=false,val instagramAccount:InstagramAccount=InstagramAccount(),val instagramType:InstagramPublishType=InstagramPublishType.STORY,val instagramStatus:InstagramPublishStatus=InstagramPublishStatus.IDLE,val instagramResult:InstagramPublishResult?=null,val instagramRequestId:String?=null,val prophecy:QrProphecy?=null,val prophecyLoading:Boolean=false,val audiences:List<AudienceEntry> = emptyList(),val notificationScheduled:Boolean=false,val session:PerformanceSession?=null,val dialogue:AiDialogue?=null,val revealStep:Int=0,val rehearsal:List<RehearsalAttempt> = emptyList(),val history:List<PerformanceHistory> = emptyList(),val smartDeck:SmartDeckSnapshot=SmartDeckSnapshot(),val smartDeckSettings:SmartDeckSettings=SmartDeckSettings(),val smartDeckCandidates:List<SmartDeckCandidate> = emptyList(),val smartDeckLog:List<String> = emptyList())
class CardCallerViewModel(app:Application):AndroidViewModel(app) {
    private val settingsRepo=SettingsRepository(app);private val smartSettingsRepo=SmartDeckSettingsRepository(app); private val remote:RemoteCardRepository=FirebaseRemoteCardRepository(); private val instagram:InstagramPublishRepository=FastApiInstagramRepository();private val magicLab:MagicLabRepository=FastApiMagicLabRepository();private val historyRepo:PerformanceHistoryRepository=RoomPerformanceHistoryRepository(CardCallerDatabase.get(app).history()); private var callJob:Job?=null;private var listenJob:Job?=null;private var smartBindJob:Job?=null;private var smartEventJob:Job?=null;private var reconnectJob:Job?=null;private var ledOffJob:Job?=null;private val dedupe=MessageDeduplicator();private val sensorGate=SensorEventGate();private var smartDevice:SmartDeckDevice=FakeSmartDeckDevice();private var smartBound=false;private var finaleArmed=false
    private val _ui=MutableStateFlow(UiState());val ui:StateFlow<UiState> = _ui.asStateFlow()
    init { viewModelScope.launch { settingsRepo.settings.collect{_ui.update{s->s.copy(settings=it)}} };viewModelScope.launch{historyRepo.observe().collect{items->_ui.update{it.copy(history=items)}}};viewModelScope.launch{smartSettingsRepo.settings.collect{s->_ui.update{it.copy(smartDeckSettings=s)};bindSmartDevice(s.fakeDevice);if(s.autoConnect&&s.lastDeviceId.isNotBlank())runCatching{smartDevice.connect(s.lastDeviceId)}}} }
    fun navigate(s:Screen){_ui.update{it.copy(screen=s,error=null)};if(s==Screen.INSTAGRAM)loadInstagramAccount()}
    fun openRemotePicker()=_ui.update{it.copy(screen=Screen.PICKER,remoteMode=true,error=null)}
    fun select(c:PlayingCard,inputMethod:String="DIRECT")=_ui.update{it.copy(selected=c,lastCard=c,session=advanceToCard(it.session,c).copy(inputMethod=inputMethod))}
    fun clearSelection()=_ui.update{it.copy(selected=null,gestureSuit=null,taps=0,session=null)}
    fun schedule(delaySeconds:Int=_ui.value.settings.delaySeconds){val c=_ui.value.selected?:return fail("카드가 선택되지 않았습니다");if(_ui.value.screen==Screen.WAITING)return;callJob?.cancel();_ui.update{it.copy(session=it.session?.copy(triggerMethod="DELAY_${delaySeconds.coerceIn(0,60)}S"))};if(!event(PerformanceEvent.Schedule))return;_ui.update{it.copy(screen=Screen.WAITING)};callJob=viewModelScope.launch{delay(delaySeconds.coerceIn(0,60)*1000L);if(event(PerformanceEvent.Ring))_ui.update{it.copy(screen=Screen.INCOMING,selected=c)}}}
    fun triggerNow(){if(_ui.value.selected==null)return fail("카드가 선택되지 않았습니다");callJob?.cancel();_ui.update{it.copy(session=it.session?.copy(triggerMethod="IMMEDIATE"))};if(_ui.value.session?.state==PerformanceState.CARD_SELECTED&&!event(PerformanceEvent.Schedule))return;if(event(PerformanceEvent.Ring))_ui.update{it.copy(screen=Screen.INCOMING)}}
    fun accept(){if(!event(PerformanceEvent.Accept))return;_ui.update{it.copy(screen=Screen.AI_CALL,revealStep=0)};generateDialogue()}
    fun reject(){event(PerformanceEvent.Cancel);persistSession();home()}
    fun home(){callJob?.cancel();_ui.update{UiState(settings=it.settings,selected=if(it.settings.clearLastCard)null else it.selected,lastCard=it.lastCard,instagramAccount=it.instagramAccount,prophecy=it.prophecy,audiences=it.audiences,history=it.history,smartDeck=it.smartDeck,smartDeckSettings=it.smartDeckSettings,smartDeckCandidates=it.smartDeckCandidates)}}
    fun gestureSuit(s:Suit)=_ui.update{it.copy(gestureSuit=s)}
    fun tap(){_ui.update{it.copy(taps=(it.taps+1).coerceAtMost(13))};completeGesture()}
    fun resetGesture()=_ui.update{it.copy(gestureSuit=null,taps=0,selected=null,session=null)}
    private fun completeGesture(){val u=_ui.value;val r=GestureInputManager.rank(u.taps);if(u.gestureSuit!=null&&r!=null)select(PlayingCard(u.gestureSuit,r),"GESTURE")}
    fun saveSettings(s:AppSettings)=viewModelScope.launch{settingsRepo.update(s)}
    fun createRoom(){if(!remote.available){_ui.update{it.copy(error="Firebase 설정이 필요합니다")};return};listenJob=viewModelScope.launch{runCatching{remote.createRoom()}.onSuccess{code->_ui.update{it.copy(roomCode=code,connection=ConnectionState.CONNECTED)};listen(code)}.onFailure{e->_ui.update{it.copy(error=e.message,connection=ConnectionState.DISCONNECTED)}}}}
    fun join(code:String){if(!RoomCode.valid(code)){_ui.update{it.copy(error="6자리 방 코드를 입력하세요")};return};_ui.update{it.copy(roomCode=code,connection=ConnectionState.CONNECTED)};listen(code)}
    fun sendRemote(c:PlayingCard)=viewModelScope.launch{runCatching{remote.send(_ui.value.roomCode,c)}.onFailure{e->_ui.update{it.copy(error=e.message)}}}
    private fun loadInstagramAccount()=viewModelScope.launch{runCatching{instagram.account()}.onSuccess{a->_ui.update{it.copy(instagramAccount=a)}}.onFailure{e->_ui.update{it.copy(error=e.message)}}}
    fun confirmInstagram(type:InstagramPublishType)=_ui.update{it.copy(instagramType=type,instagramStatus=InstagramPublishStatus.CONFIRMING,error=null)}
    fun cancelInstagramConfirm()=_ui.update{it.copy(instagramStatus=InstagramPublishStatus.IDLE)}
    fun publishInstagram(retry:Boolean=false){val card=_ui.value.selected?:_ui.value.lastCard?:return;val id=if(retry)_ui.value.instagramRequestId?:java.util.UUID.randomUUID().toString() else java.util.UUID.randomUUID().toString();_ui.update{it.copy(instagramStatus=if(retry)InstagramPublishStatus.RETRYING else InstagramPublishStatus.PUBLISHING,instagramRequestId=id,error=null)};viewModelScope.launch{runCatching{instagram.publish(card,_ui.value.instagramType,id)}.onSuccess{r->_ui.update{it.copy(instagramStatus=r.status,instagramResult=r)}}.onFailure{e->_ui.update{it.copy(instagramStatus=InstagramPublishStatus.FAILED,error=e.message,instagramResult=InstagramPublishResult(id,InstagramPublishStatus.FAILED,error=e.message))}}}}
    fun setLabMode(mode:LabMode){val next=_ui.value.settings.copy(labMode=mode);_ui.update{it.copy(settings=next)};saveSettings(next)}
    fun createProphecy(withCard:Boolean=true)=viewModelScope.launch{_ui.update{it.copy(prophecyLoading=true,error=null)};val card=(_ui.value.selected?:_ui.value.lastCard).takeIf{withCard};runCatching{magicLab.createProphecy(card,_ui.value.settings.qrExpiryMinutes)}.onSuccess{p->_ui.update{it.copy(prophecy=p,prophecyLoading=false)}}.onFailure{e->_ui.update{it.copy(prophecyLoading=false,error=e.message)}}}
    fun setProphecyCard()=viewModelScope.launch{val p=_ui.value.prophecy?:return@launch;val card=_ui.value.selected?:_ui.value.lastCard?:return@launch;runCatching{magicLab.setCard(p,card)}.onSuccess{n->_ui.update{it.copy(prophecy=n)}}.onFailure{e->_ui.update{it.copy(error=e.message)}}}
    fun scheduleNotification(delay:Int){val card=_ui.value.selected?:_ui.value.lastCard?:return;CardNotificationWorker.schedule(getApplication(),card,_ui.value.settings.notificationTitle,_ui.value.settings.notificationContent,delay);_ui.update{it.copy(notificationScheduled=true)}}
    fun addAudience(name:String)=viewModelScope.launch{val card=_ui.value.selected?:_ui.value.lastCard;runCatching{magicLab.createProphecy(card,_ui.value.settings.qrExpiryMinutes)}.onSuccess{p->_ui.update{it.copy(audiences=it.audiences+AudienceEntry(name,p,card))}}.onFailure{e->_ui.update{it.copy(error=e.message)}}}
    fun refreshAudiences()=viewModelScope.launch{val refreshed=_ui.value.audiences.map{entry->runCatching{val p=magicLab.status(entry.prophecy);entry.copy(prophecy=p,revealed=p.consumed)}.getOrDefault(entry)};_ui.update{it.copy(audiences=refreshed)}}
    fun startDemo(index:Int){val cards=listOf(PlayingCard(Suit.SPADES,Rank.SEVEN),PlayingCard(Suit.HEARTS,Rank.QUEEN),PlayingCard(Suit.CLUBS,Rank.ACE));val c=cards[index.coerceIn(0,2)];select(c);schedule(listOf(5,0,0)[index.coerceIn(0,2)])}
    fun nextDialogue(){val n=(_ui.value.revealStep+1).coerceAtMost(4);_ui.update{it.copy(revealStep=n)};if(n==4)viewModelScope.launch{delay(900);if(event(PerformanceEvent.Reveal))_ui.update{it.copy(screen=Screen.REVEAL)}}}
    fun openResult(){if(_ui.value.session?.state!=PerformanceState.REVEALING)return fail("카드 공개가 완료되지 않았습니다");_ui.update{it.copy(screen=Screen.RESULT)};activateSmartDeckFinale()}
    fun finishPerformance(reaction:String,success:Boolean=true){val s=_ui.value.session?.copy(reaction=reaction,success=success)?:return;if(!event(PerformanceEvent.Complete,s))return;persistSession()}
    fun clearHistory()=viewModelScope.launch{historyRepo.clear()}
    fun recordRehearsal(expected:PlayingCard,actual:PlayingCard?,method:String,durationMs:Long)=_ui.update{it.copy(rehearsal=it.rehearsal+RehearsalAttempt(expected.id,actual?.id,method,durationMs))}
    private val volumeInput=VolumeSecretInputController()
    fun volumeSecret(key:VolumeKey){volumeInput.input(key)?.let{select(it,"VOLUME")}}
    private fun generateDialogue(){val c=_ui.value.selected?:return;viewModelScope.launch{_ui.update{it.copy(dialogue=SafeDialogueGenerator(null).generate(c,it.settings.ttsLanguage,"MENTALIST"))}}}
    private fun advanceToCard(session:PerformanceSession?,card:PlayingCard):PerformanceSession {var s=session?:PerformanceSession();if(s.state==PerformanceState.CREATED)s=PerformanceStateMachine.transition(s,PerformanceEvent.Configure)!!;if(s.state==PerformanceState.READY)s=PerformanceStateMachine.transition(s,PerformanceEvent.AwaitInput)!!;return PerformanceStateMachine.transition(s,PerformanceEvent.SelectCard(card))?:s.copy(card=card,state=PerformanceState.CARD_SELECTED)}
    private fun event(e:PerformanceEvent,base:PerformanceSession?=_ui.value.session):Boolean{val s=base?:return fail("공연 세션이 없습니다").let{false};val next=PerformanceStateMachine.transition(s,e)?:return fail("허용되지 않은 상태 전이: ${s.state} → ${e::class.simpleName}").let{false};_ui.update{it.copy(session=next,error=null)};return true}
    private fun fail(message:String){_ui.update{it.copy(error=message,session=it.session?.let{s->PerformanceStateMachine.transition(s,PerformanceEvent.Fail)?:s})}}
    private fun persistSession(){_ui.value.session?.let{s->viewModelScope.launch{historyRepo.save(s)}}}
    fun saveSmartDeckSettings(s:SmartDeckSettings)=viewModelScope.launch{smartSettingsRepo.save(s)}
    fun scanSmartDeck()=viewModelScope.launch{runCatching{smartDevice.scan()}.onSuccess{items->_ui.update{it.copy(smartDeckCandidates=items)}}.onFailure{failSmartDeck(it.message?:"SCAN_FAILED")}}
    fun connectSmartDeck(candidate:SmartDeckCandidate)=viewModelScope.launch{runCatching{smartDevice.connect(candidate.id);smartSettingsRepo.save(_ui.value.smartDeckSettings.copy(lastDeviceId=candidate.id))}.onFailure{failSmartDeck(it.message?:"CONNECT_FAILED")}}
    fun disconnectSmartDeck()=viewModelScope.launch{smartDevice.disconnect()}
    fun armSmartDeck(armed:Boolean)=viewModelScope.launch{smartDevice.send(if(armed)SmartDeckCommand.Arm else SmartDeckCommand.Disarm)}
    fun smartDeckLed(on:Boolean)=viewModelScope.launch{if(on)executeCardEffect(false) else{ledOffJob?.cancel();smartDevice.send(SmartDeckCommand.LedOff)}}
    fun smartDeckFinale()=viewModelScope.launch{executeCardEffect(true)}
    fun fakeDeckEvent(open:Boolean)=viewModelScope.launch{(smartDevice as? FakeSmartDeckDevice)?.emit(if(open)SmartDeckEvent.DeckOpen(87) else SmartDeckEvent.DeckClosed(86))}
    fun smartDeckVolume(up:Boolean,long:Boolean=false):Boolean{if(_ui.value.smartDeckSettings.secretControl!=SecretDeckControl.VOLUME)return false;if(long)smartDeckFinale() else smartDeckLed(up);return true}
    private fun activateSmartDeckFinale(){if(_ui.value.smartDeckSettings.mode!=SmartDeckMode.FINALE)return;finaleArmed=true;appendDeckLog("피날레 준비");if(_ui.value.smartDeck.deckOpen)smartDeckFinale()}
    private suspend fun executeCardEffect(finale:Boolean){val settings=_ui.value.smartDeckSettings.sanitized();if(!smartDevice.snapshot.value.connected)return failSmartDeck("DEVICE_DISCONNECTED");if(settings.mode in listOf(SmartDeckMode.DELAYED,SmartDeckMode.FINALE))delay(selectedDelay(settings).toLong());val card=_ui.value.selected?:_ui.value.lastCard;val brightness=if((smartDevice.snapshot.value.battery?:100)<15)settings.brightness.coerceAtMost(35)else settings.brightness;smartDevice.send(SmartDeckCommand.SetMaxOn(settings.autoOffSeconds));SmartDeckAutomation.cardCommands(settings.copy(brightness=brightness),card,finale).forEach{smartDevice.send(it)};appendDeckLog(if(finale)"피날레 실행" else "LED 켜짐");finaleArmed=false;ledOffJob?.cancel();ledOffJob=viewModelScope.launch{delay(settings.autoOffSeconds*1000L);smartDevice.send(SmartDeckCommand.LedOff);appendDeckLog("안전 자동 종료")}}
    private fun bindSmartDevice(fake:Boolean){if(smartBound&&((fake&&smartDevice is FakeSmartDeckDevice)||(!fake&&smartDevice is AndroidSmartDeckDevice)))return;smartBindJob?.cancel();smartEventJob?.cancel();reconnectJob?.cancel();smartDevice.emergencyClose();smartDevice=if(fake)FakeSmartDeckDevice() else AndroidSmartDeckDevice(getApplication());smartBound=true;smartBindJob=viewModelScope.launch{var wasConnected=false;smartDevice.snapshot.collect{s->val disconnected=wasConnected&&!s.connected;wasConnected=s.connected;val shown=if(_ui.value.smartDeckSettings.sensorInverted&&s.lastEventAt>0)s.copy(deckOpen=!s.deckOpen)else s;_ui.update{it.copy(smartDeck=shown)};if(disconnected){vibrateDisconnect();scheduleDeckReconnect()}}};smartEventJob=viewModelScope.launch{smartDevice.events.collect(::handleDeckEvent)}}
    private fun scheduleDeckReconnect(){val settings=_ui.value.smartDeckSettings;if(!settings.autoConnect||settings.lastDeviceId.isBlank())return;reconnectJob?.cancel();reconnectJob=viewModelScope.launch{repeat(3){attempt->delay(1000L shl attempt);runCatching{smartDevice.connect(settings.lastDeviceId)};delay(1500);if(smartDevice.snapshot.value.connected)return@launch};failSmartDeck("RECONNECT_FAILED")}}
    private suspend fun handleDeckEvent(e:SmartDeckEvent){val type=e::class.simpleName?:return;if(!sensorGate.accept(type,System.currentTimeMillis()))return;appendDeckLog(type);val settings=_ui.value.smartDeckSettings;val logical=if(!settings.sensorInverted)e else when(e){is SmartDeckEvent.DeckOpen->SmartDeckEvent.DeckClosed(e.battery);is SmartDeckEvent.DeckClosed->SmartDeckEvent.DeckOpen(e.battery);else->e};when(logical){is SmartDeckEvent.DeckOpen->{if(_ui.value.smartDeck.armed&&(settings.mode!=SmartDeckMode.FINALE||finaleArmed))executeCardEffect(settings.mode==SmartDeckMode.FINALE)};is SmartDeckEvent.DeckClosed->{ledOffJob?.cancel();smartDevice.send(SmartDeckCommand.LedOff)};is SmartDeckEvent.Error->{runCatching{smartDevice.send(SmartDeckCommand.LedOff)};failSmartDeck(logical.code)};else->{}}}
    private fun appendDeckLog(message:String)=_ui.update{it.copy(smartDeckLog=(it.smartDeckLog+"${System.currentTimeMillis()}: $message").takeLast(30))}
    private fun failSmartDeck(code:String){_ui.update{it.copy(smartDeck=it.smartDeck.copy(state=SmartDeckState.ERROR,errorCode=code),error=if(it.settings.labMode==LabMode.PERFORMANCE)"장치 상태를 확인하세요" else code)}}
    private fun vibrateDisconnect(){val a=getApplication<Application>();val v=if(android.os.Build.VERSION.SDK_INT>=31)(a.getSystemService(android.content.Context.VIBRATOR_MANAGER_SERVICE)as android.os.VibratorManager).defaultVibrator else @Suppress("DEPRECATION")(a.getSystemService(android.content.Context.VIBRATOR_SERVICE)as android.os.Vibrator);v.vibrate(android.os.VibrationEffect.createOneShot(180,120))}
    override fun onCleared(){callJob?.cancel();listenJob?.cancel();smartBindJob?.cancel();smartEventJob?.cancel();reconnectJob?.cancel();ledOffJob?.cancel();smartDevice.emergencyClose();super.onCleared()}
    private fun listen(code:String){listenJob?.cancel();listenJob=viewModelScope.launch{remote.listen(code).retryWhen{_,attempt->if(attempt>=3){_ui.update{it.copy(connection=ConnectionState.DISCONNECTED,error="원격 연결 재시도에 실패했습니다")};false}else{_ui.update{it.copy(connection=ConnectionState.RECONNECTING)};delay(1000L shl attempt.toInt());true}}.collect{m->if(dedupe.shouldConsume(m.messageId)){PlayingCard.fromId(m.cardId)?.let{select(it,"REMOTE");_ui.update{u->u.copy(connection=ConnectionState.CARD_RECEIVED)};schedule()};remote.consume(code,m.messageId)}}}}
}
