package com.cardcaller.magic

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.VibrationEffect
import android.os.Vibrator
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.Crossfade
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import coil.compose.AsyncImage
import com.google.zxing.BarcodeFormat
import com.google.zxing.MultiFormatWriter
import com.google.zxing.common.BitMatrix
import kotlinx.coroutines.delay

private val LabGreen=Color(0xFF3DDC84);private val LabSurface=Color(0xFF122238);private val LabMuted=Color(0xFF9FB0C5);private val LabDanger=Color(0xFFE53935)
@Composable private fun LabPage(title:String,vm:CardCallerViewModel,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().statusBarsPadding().padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){IconButton({vm.navigate(Screen.MAGIC_LAB)}){Icon(Icons.Default.ArrowBack,"뒤로")};Text(title,fontSize=24.sp,fontWeight=FontWeight.Bold)};ModeSelector(vm);Spacer(Modifier.height(8.dp));content()}}
@Composable private fun ModeSelector(vm:CardCallerViewModel){val u by vm.ui.collectAsState();SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){LabMode.entries.forEachIndexed{i,m->SegmentedButton(selected=u.settings.labMode==m,onClick={vm.setLabMode(m)},shape=SegmentedButtonDefaults.itemShape(i,2)){Text(if(m==LabMode.PRACTICE)"연습 모드" else "공연 모드")}}}}
@Composable fun MagicLabHome(vm:CardCallerViewModel){val items=listOf("QR 카드 예언" to Screen.QR_PROPHECY,"알림 카드 예언" to Screen.NOTIFICATION_PROPHECY,"음성 전화 공개 설정" to Screen.SETTINGS,"거짓말 탐지기 마술" to Screen.LIE_DETECTOR,"사진 속 카드 출현" to Screen.PHOTO_MAGIC,"다중 관객 모드" to Screen.MULTI_AUDIENCE);LabPage("Magic Lab",vm){items.forEach{(name,screen)->Card(Modifier.fillMaxWidth().padding(vertical=5.dp).clickable{vm.navigate(screen)},colors=CardDefaults.cardColors(containerColor=LabSurface)){Text(name,Modifier.padding(18.dp),fontSize=18.sp)}};Spacer(Modifier.weight(1f));Text("공연 모드에서는 비밀 카드가 관객 화면에 표시되지 않습니다.",color=LabMuted,fontSize=12.sp)}}
@Composable fun QrProphecyScreen(vm:CardCallerViewModel,u:UiState){LabPage("QR 카드 예언",vm){val card=u.selected?:u.lastCard;if(u.prophecyLoading){Box(Modifier.weight(1f).fillMaxWidth(),contentAlignment=Alignment.Center){CircularProgressIndicator()}}else{u.prophecy?.let{p->Column(Modifier.weight(1f).fillMaxWidth(),horizontalAlignment=Alignment.CenterHorizontally){Text("방 코드 ${p.roomCode}",fontSize=27.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(14.dp));QrImage(p.qrUrl,260);Text("${u.settings.qrExpiryMinutes}분 후 만료 · 일회용",color=LabMuted);if(u.settings.labMode==LabMode.PRACTICE)Text("비밀 카드: ${card?.display(CardDisplayFormat.KOREAN)?:"미설정"}",color=LabGreen);if(p.cardId==null&&card!=null)Button(vm::setProphecyCard){Text("현재 카드 설정")}}}?:Box(Modifier.weight(1f).fillMaxWidth(),contentAlignment=Alignment.Center){Text(if(card==null)"카드 없이 QR을 먼저 만들 수 있습니다" else "선택 카드로 일회용 예언을 만드세요",color=LabMuted)}};Button(onClick={vm.createProphecy(card!=null)},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("새 일회용 QR 만들기")};u.error?.let{Text(it,color=LabDanger)}}}
@Composable private fun QrImage(value:String,size:Int){val bitmap=remember(value){val matrix=MultiFormatWriter().encode(value,BarcodeFormat.QR_CODE,size,size);android.graphics.Bitmap.createBitmap(size,size,android.graphics.Bitmap.Config.RGB_565).apply{for(y in 0 until size)for(x in 0 until size)setPixel(x,y,if(matrix[x,y])android.graphics.Color.BLACK else android.graphics.Color.WHITE)}};Image(bitmap.asImageBitmap(),"일회용 예언 QR 코드",Modifier.size(size.dp).padding(8.dp))}
@Composable fun NotificationProphecyScreen(vm:CardCallerViewModel,u:UiState){val context=LocalContext.current;var settings by remember(u.settings){mutableStateOf(u.settings)};var delayValue by remember{mutableIntStateOf(settings.notificationDelay)};var pending by remember{mutableIntStateOf(0)};val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->if(granted)vm.scheduleNotification(pending)};fun schedule(){val card=u.selected?:u.lastCard;if(card==null)return;pending=delayValue;if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(context,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permission.launch(Manifest.permission.POST_NOTIFICATIONS)else vm.scheduleNotification(delayValue)};LabPage("알림 카드 예언",vm){Column(Modifier.weight(1f).verticalScroll(rememberScrollState())){if(u.settings.labMode==LabMode.PRACTICE)Text("카드: ${(u.selected?:u.lastCard)?.display(CardDisplayFormat.KOREAN)?:"미선택"}",color=LabGreen);OutlinedTextField(settings.notificationTitle,{settings=settings.copy(notificationTitle=it)},label={Text("알림 제목")},modifier=Modifier.fillMaxWidth());OutlinedTextField(settings.notificationContent,{settings=settings.copy(notificationContent=it)},label={Text("알림 내용 (%CARD% 사용)")},modifier=Modifier.fillMaxWidth());Text("공개 지연: ${delayValue}초");Row(Modifier.horizontalScroll(rememberScrollState())){listOf(0,3,5,10).forEach{d->FilterChip(delayValue==d,{delayValue=d},label={Text(if(d==0)"즉시" else "${d}초")},modifier=Modifier.padding(end=6.dp))}};Text("사용자 지정");Slider(delayValue.toFloat(),{delayValue=it.toInt()},valueRange=0f..60f);if(u.notificationScheduled)Text("알림이 예약되었습니다",color=LabGreen)};Button(onClick={vm.saveSettings(settings.copy(notificationDelay=delayValue));schedule()},Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("실제 알림 예약")}}}
@Composable fun LieDetectorScreen(vm:CardCallerViewModel,u:UiState){val context=LocalContext.current;val questions=listOf("카드는 빨간색입니까?","카드 무늬는 하트 또는 다이아몬드입니까?","카드 숫자는 7보다 큽니까?");var step by remember{mutableIntStateOf(0)};var scanning by remember{mutableStateOf(false)};var done by remember{mutableStateOf(false)};fun answer(){if(step<questions.lastIndex)step++ else scanning=true};LaunchedEffect(scanning){if(scanning){repeat(5){(context.getSystemService(android.content.Context.VIBRATOR_SERVICE)as Vibrator).vibrate(VibrationEffect.createOneShot(60,80));delay(300)};scanning=false;done=true}};LabPage("거짓말 탐지기 마술",vm){Box(Modifier.weight(1f).fillMaxWidth(),contentAlignment=Alignment.Center){when{done->Column(horizontalAlignment=Alignment.CenterHorizontally){Text("탐지 결과",color=LabMuted);Text((u.selected?:u.lastCard)?.display(CardDisplayFormat.KOREAN)?:"카드 미설정",fontSize=36.sp,fontWeight=FontWeight.Bold,color=LabGreen)};scanning->Column(horizontalAlignment=Alignment.CenterHorizontally){CircularProgressIndicator();Text("답변을 분석하고 있습니다…")};else->Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.Fingerprint,null,Modifier.size(90.dp),tint=LabGreen);Text(questions[step],fontSize=24.sp);Row{Button(onClick={answer()},Modifier.padding(8.dp)){Text("예")};OutlinedButton(onClick={answer()},Modifier.padding(8.dp)){Text("아니요")}};if(u.settings.labMode==LabMode.PRACTICE)Text("강제 카드: ${(u.selected?:u.lastCard)?.display(CardDisplayFormat.KOREAN)?:"미선택"}",color=LabMuted)}}};Text("실제 생체정보를 측정하지 않는 공연용 시뮬레이션입니다.",color=LabMuted,fontSize=12.sp)}}
@Composable fun PhotoMagicScreen(vm:CardCallerViewModel,u:UiState){val context=LocalContext.current;val card=u.selected?:u.lastCard;var photo by remember{mutableStateOf<Uri?>(null)};var cameraUri by remember{mutableStateOf<Uri?>(null)};var transform by remember{mutableStateOf(OverlayTransform())};var saved by remember{mutableStateOf<Uri?>(null)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.PickVisualMedia()){photo=it};val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()){ok->if(ok)photo=cameraUri};LabPage("사진 속 카드 출현",vm){Crossfade(photo,Modifier.weight(1f).fillMaxWidth()){uri->if(uri==null)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column{Button({picker.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))}){Text("사진 선택")};OutlinedButton({cameraUri=PhotoComposer.cameraUri(context);camera.launch(cameraUri!!)}){Text("사진 촬영")}}}else Column(Modifier.verticalScroll(rememberScrollState())){Box(Modifier.fillMaxWidth().aspectRatio(1f).background(Color.Black)){AsyncImage(uri,null,Modifier.fillMaxSize());card?.let{c->Card(Modifier.align(Alignment.TopStart).offset((transform.x*240).dp,(transform.y*240).dp).size((180*transform.scale).dp,(260*transform.scale).dp).graphicsLayer{rotationZ=transform.rotation;alpha=transform.alpha;shadowElevation=transform.shadow},colors=CardDefaults.cardColors(containerColor=Color.White)){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("${c.suit.symbol} ${c.rank.label}",color=if(c.suit in listOf(Suit.HEARTS,Suit.DIAMONDS))Color.Red else Color.Black,fontWeight=FontWeight.Bold)}}}};PhotoSlider("가로 위치",transform.x,0f..1f){transform=transform.copy(x=it)};PhotoSlider("세로 위치",transform.y,0f..1f){transform=transform.copy(y=it)};PhotoSlider("크기",transform.scale,.15f..1f){transform=transform.copy(scale=it)};PhotoSlider("회전",transform.rotation,-180f..180f){transform=transform.copy(rotation=it)};PhotoSlider("투명도",transform.alpha,.2f..1f){transform=transform.copy(alpha=it)};PhotoSlider("그림자",transform.shadow,0f..30f){transform=transform.copy(shadow=it)}}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick={if(photo!=null&&card!=null)saved=PhotoComposer.composeAndSave(context,photo!!,card,transform)},Modifier.weight(1f)){Text("기기에 저장")};Button(onClick={saved?.let{context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type="image/jpeg";putExtra(Intent.EXTRA_STREAM,it);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)},"합성 이미지 공유"))}},enabled=saved!=null,modifier=Modifier.weight(1f)){Text("공유")}}}}
@Composable private fun PhotoSlider(name:String,value:Float,range:ClosedFloatingPointRange<Float>,set:(Float)->Unit){Text("$name: ${"%.1f".format(value)}");Slider(value,set,valueRange=range)}
@Composable fun MultiAudienceScreen(vm:CardCallerViewModel,u:UiState){var name by remember{mutableStateOf("")};LabPage("다중 관객 모드",vm){Row{OutlinedTextField(name,{name=it},label={Text("관객 이름")},modifier=Modifier.weight(1f));IconButton(onClick={if(name.isNotBlank()){vm.addAudience(name);name=""}}){Icon(Icons.Default.PersonAdd,"관객 추가")}};Row{Text("관객별 독립 방/QR",Modifier.weight(1f),color=LabMuted);TextButton(vm::refreshAudiences){Text("상태 새로고침")}};LazyColumn(Modifier.weight(1f)){items(u.audiences){entry->Card(Modifier.fillMaxWidth().padding(vertical=5.dp),colors=CardDefaults.cardColors(containerColor=LabSurface)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){QrImage(entry.prophecy.qrUrl,92);Column(Modifier.weight(1f)){Text(entry.name,fontWeight=FontWeight.Bold);Text("방 ${entry.prophecy.roomCode}");Text(if(entry.revealed)"공개됨" else "대기 중",color=if(entry.revealed)LabGreen else LabMuted);if(u.settings.labMode==LabMode.PRACTICE)Text(entry.card?.display(CardDisplayFormat.KOREAN)?:"카드 미설정",color=LabGreen)}}}}};Text("각 QR은 한 번만 공개되며 소비된 명령은 다시 실행되지 않습니다.",fontSize=12.sp,color=LabMuted)}}
