package com.cardcaller.magic
import org.junit.Assert.*
import org.junit.Test
class CoreTests {
 @Test fun deckHas52CardsAndTwoJokers(){assertEquals(54,PlayingCard.deck.size);assertEquals(54,PlayingCard.deck.map{it.id}.toSet().size);assertNotNull(PlayingCard.fromId("JR"));assertNotNull(PlayingCard.fromId("JB"))}
 @Test fun idRoundTrip(){PlayingCard.deck.forEach{assertEquals(it,PlayingCard.fromId(it.id))}}
 @Test fun tapMapping(){assertEquals(Rank.ACE,GestureInputManager.rank(1));assertEquals(Rank.TEN,GestureInputManager.rank(10));assertEquals(Rank.KING,GestureInputManager.rank(13))}
 @Test fun invalidTaps(){assertNull(GestureInputManager.rank(0));assertNull(GestureInputManager.rank(14))}
 @Test fun dragMapping(){assertEquals(Suit.SPADES,GestureInputManager.suit(0f,-100f,50f));assertEquals(Suit.HEARTS,GestureInputManager.suit(100f,0f,50f));assertEquals(Suit.CLUBS,GestureInputManager.suit(0f,100f,50f));assertEquals(Suit.DIAMONDS,GestureInputManager.suit(-100f,0f,50f));assertNull(GestureInputManager.suit(2f,3f,50f))}
 @Test fun duplicateConsumption(){val d=MessageDeduplicator();assertTrue(d.shouldConsume("x"));assertFalse(d.shouldConsume("x"))}
 @Test fun roomCodes(){repeat(100){assertTrue(RoomCode.valid(RoomCode.generate()))};assertFalse(RoomCode.valid("123"));assertFalse(RoomCode.valid("abcdef"))}
 @Test fun notificationTemplateRevealsSelectedCard(){assertEquals("예언: 하트 에이스",MagicLabLogic.notificationContent("예언: %CARD%",PlayingCard(Suit.HEARTS,Rank.ACE)))}
 @Test fun ttsSupportsKoreanAndEnglish(){val c=PlayingCard(Suit.SPADES,Rank.KING);assertTrue(MagicLabLogic.ttsPhrase(c,TtsLanguage.KOREAN).contains("스페이드 킹"));assertTrue(MagicLabLogic.ttsPhrase(c,TtsLanguage.ENGLISH).contains("KING OF SPADES"))}
 @Test fun lieDetectorAlwaysReturnsPreselectedCard(){val c=PlayingCard(Suit.CLUBS,Rank.SEVEN);assertEquals(c,MagicLabLogic.forcedLieDetectorResult(c,listOf(true,false,true)))}
 @Test fun photoTransformIsConstrained(){val t=MagicLabLogic.sanitizeTransform(OverlayTransform(x=2f,y=-1f,alpha=3f,rotation=300f,shadow=-4f));assertEquals(1f,t.x);assertEquals(0f,t.y);assertEquals(1f,t.alpha);assertEquals(180f,t.rotation);assertEquals(0f,t.shadow)}
 @Test fun stateMachineRejectsInvalidTransitions(){val s=PerformanceSession();assertNull(PerformanceStateMachine.transition(s,PerformanceEvent.Ring));val ready=PerformanceStateMachine.transition(s,PerformanceEvent.Configure)!!;assertEquals(PerformanceState.READY,ready.state)}
 @Test fun stateMachineRunsHappyPath(){var s=PerformanceSession();s=PerformanceStateMachine.transition(s,PerformanceEvent.Configure)!!;s=PerformanceStateMachine.transition(s,PerformanceEvent.AwaitInput)!!;s=PerformanceStateMachine.transition(s,PerformanceEvent.SelectCard(PlayingCard(Suit.SPADES,Rank.SEVEN)))!!;s=PerformanceStateMachine.transition(s,PerformanceEvent.Schedule)!!;s=PerformanceStateMachine.transition(s,PerformanceEvent.Ring)!!;s=PerformanceStateMachine.transition(s,PerformanceEvent.Accept)!!;assertEquals(PerformanceState.CONNECTED,s.state)}
 @Test fun volumeCombinationMapsCard(){val c=VolumeSecretInputController();assertNull(c.input(VolumeKey.UP,1));assertNull(c.input(VolumeKey.UP,2));repeat(7){assertNull(c.input(VolumeKey.DOWN,(3+it).toLong()))};assertEquals(PlayingCard(Suit.HEARTS,Rank.SEVEN),c.input(VolumeKey.UP,11))}
 @Test fun voiceCodeParsesNaturalPhrase(){assertEquals(PlayingCard(Suit.SPADES,Rank.SEVEN),VoiceCodeParser.parse("검은 창문이 인상적이고 오늘 일곱 번째 손님이네요"))}
 @Test fun rehearsalStatisticsUseRealAttempts(){val xs=listOf(RehearsalAttempt("A","A","touch",1000),RehearsalAttempt("A","B","touch",3000));assertEquals(50.0,RehearsalStats.accuracy(xs),0.01);assertEquals(2.0,RehearsalStats.averageSeconds(xs),0.01)}
 @Test fun cardIdsAndShortCodesAreUnique(){assertEquals(PlayingCard.deck.size,PlayingCard.deck.map{it.id}.toSet().size);assertEquals(PlayingCard.deck.size,PlayingCard.deck.map{it.shortCode}.toSet().size)}
 @Test fun cancelledAndFailedAreTerminal(){val s=PerformanceSession();assertEquals(PerformanceState.CANCELLED,PerformanceStateMachine.transition(s,PerformanceEvent.Cancel)?.state);assertEquals(PerformanceState.FAILED,PerformanceStateMachine.transition(s,PerformanceEvent.Fail)?.state)}
 @Test fun callerAndDelayValidation(){assertEquals("123456789012345678901234567890",CallerSettings.sanitizeName("  123456789012345678901234567890xxx "));assertNull(CallerSettings.delay("99"));assertNull(CallerSettings.delay("abc"));assertNull(CallerSettings.delay("-1"))}
 @Test fun volumeInputTimesOut(){val c=VolumeSecretInputController(100);c.input(VolumeKey.UP,1);c.input(VolumeKey.DOWN,50);assertNull(c.input(VolumeKey.UP,200))}
 @Test fun performanceDurationNeverNegative(){assertEquals(2500L,performanceDuration(1000,3500));assertEquals(0L,performanceDuration(5000,1000))}
 @Test fun rehearsalAnalyticsFindsMostMissedAndGroups(){val xs=listOf(RehearsalAttempt("SPADES_SEVEN","HEARTS_SEVEN","touch",1000),RehearsalAttempt("SPADES_SEVEN",null,"touch",2000),RehearsalAttempt("HEARTS_ACE","HEARTS_ACE","touch",3000));val s=RehearsalAnalytics.summarize(xs);assertEquals("SPADES_SEVEN",s.mostMissedCard);assertEquals(0.0,s.bySuit["SPADES"]!!,0.01);assertEquals(100.0,s.byRank["ACE"]!!,0.01)}
 @Test fun customColorsFallbackAndBlueFanExists(){assertEquals("#07111F",ThemeSettings.validColor("oops","#07111F"));assertTrue(CallTheme.entries.contains(CallTheme.BLUE_FAN))}
 @Test fun historySummaryAndCsvContainNoPersonalFields(){val h=listOf(PerformanceHistory("1","SPADES_ACE","GESTURE","DELAY",100,1100,1000,"👏",PerformanceState.COMPLETED.name,true),PerformanceHistory("2","SPADES_ACE","GESTURE","DELAY",200,2200,2000,"😐",PerformanceState.COMPLETED.name,false));val summary=HistoryAnalytics.summarize(h);assertEquals(2,summary.cardUsage["SPADES_ACE"]);assertEquals(50.0,summary.inputSuccess["GESTURE"]!!,0.01);assertEquals(1,HistoryAnalytics.between(h,50,150).size);assertFalse(HistoryCsv.encode(h).contains("phone",true))}
}
